### PR TITLE
Feat/91 display control

### PR DESCRIPTION
**Pull request by Sm00g15**

### CODE REVIEW

**Comment by umurb** [comment]
1. Footer and Header of the dropdown list:

screen shot 2019-01-31 at 6 01 06 pm

2. Fade in/out effect

screen shot 2019-01-31 at 6 08 14 pm

You may refer to this [PR](https://github.com/Cryptonomic/Tezori/pull/369) by developer0623 to see how he implemented this for the language dropdown list in Tezori.

3. Horizontal scrolling

Horizontal scrolling looks broken. The reason we are allowing up to 6 columns is to avoid horizontal scrolling at all. But it won't be possible until we implement the dot representation of hashes. For now, let's make the Header, Footer and Field panel sticky and only make data panel to be horizontally scrolled

screen shot 2019-01-31 at 6 11 31 pm

**Comment by umurb** [comment]
Looking great. Here are some final notes and requests. After these, we can merge the PR and address tiny details later during polishing.

columns

1. Let's make the cursor default when hovering over **Select Up to 6 Columns to display** label
2. The Fade Out is selectable (see above gif)
3. Let's not allow more than 6 Columns to be selected. If 6 boxes are already selected, the cursor should not become a pointer when hovering over empty boxes, and empty boxes should not be clickable. Only selected boxes should be clickable so that the user can deselect it.
4. Hitting `Cancel` should not update the state. See above gif, where there is only 1 column is selected. Then I go ahead and select 3 more boxes and hit `cancel` to close the list. When I reopen the list, I still see 4 boxes as selected.

**Comment by developer0623** [comment]
@Sm00g15 There is `customtable` component on components folder.
I think it is better to move to container folder.

**Comment by developer0623** [comment]
check

**Comment by developer0623** [comment]
close

**Pull request merged**
