### PR TITLE
Feature/modifying structure

### PR DESCRIPTION
**Pull request by developer0623**

### CODE REVIEW

**Comment by umurb** [comment]
None of the buttons are working in this branch; `Refresh`, `Blocks`, `Operations`, `Accounts`...

**Comment by developer0623** [comment]
@umurb I fixed it

**Comment by umurb** [comment]
@developer0623 can you resolve the conflicts so that I can merge this PR?

**Comment by anonymoussprocket** [comment]
Superseded by 69

**Pull request closed without merging**
